### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ZaDarkSide** [padraigfl/packard-belle#5]
Hello!

Very nice project and great work!
But I'm wondering what type of license does the code have?

**Comment by padraigfl** [comment]
Thanks!

I would imagine the icons and potentially a lot of other things are copyrighted to Microsoft so it so I haven't really thought about it at all to be honest. As far as I'm concerned whoever can do whatever with it, it'd be nice to get a thanks or whatever in the docs but I'm not going to lose sleep over it!

If you think it should include a license I'll look into it!  Reckon MIT would be okay?

[P.S. haven't really had a chance to work on this in months, but I'm hoping to update a few bits over the next month or two 🤞. If something's broken there's a decent chance I've had some ideas for a fix over the last couple of months.]

**Comment by padraigfl** [comment]
Have added a license in recent merge, possibly not a very good one but hopefully okay 😬

**Comment by ZaDarkSide** [comment]
MIT is okay, thanks.
